spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3307/spring-boot?characterEncoding=utf8&useSSL=true
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
management:
  security:
    enabled: true
    roles: ADMIN
  context-path: /manage
  port: 10001
security:
  user:
    password: 123456
    name: admin
info:
  app:
    name: boot-sample
    version: 1.0
logging:
  path: E://log


